-- MySQL Script generated by MySQL Workbench
-- 2014年12月20日 星期六 14时36分03秒
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hello
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hello` DEFAULT CHARACTER SET utf8 ;
USE `hello` ;

-- -----------------------------------------------------
-- Table `hello`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hello`.`member` ;

CREATE TABLE IF NOT EXISTS `hello`.`member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `age` INT NULL,
  `birthday` DATE NULL,
  `province` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `last_seen_time` DATE NULL,
  `avatar_path` VARCHAR(256) NULL,
  `credits` INT NULL COMMENT '积分',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hello`.`member_has_friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hello`.`member_has_friend` ;

CREATE TABLE IF NOT EXISTS `hello`.`member_has_friend` (
  `member_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  INDEX `fk_member_has_member_member1_idx` (`friend_id` ASC),
  INDEX `fk_member_has_member_member_idx` (`member_id` ASC),
  CONSTRAINT `fk_member_has_member_member`
    FOREIGN KEY (`member_id`)
    REFERENCES `hello`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_member_member1`
    FOREIGN KEY (`friend_id`)
    REFERENCES `hello`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '朋友关系表';


-- -----------------------------------------------------
-- Table `hello`.`chat_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hello`.`chat_record` ;

CREATE TABLE IF NOT EXISTS `hello`.`chat_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `time` DATE NULL,
  `content` TEXT NULL,
  `target_member_email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chat_record_member1_idx` (`member_id` ASC),
  CONSTRAINT `fk_chat_record_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `hello`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '聊天记录';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
